import type { Metadata } from "next";
import { ClashDisplay } from "@/utils/customFonts";

import "./globals.css";
import { ThemeProvider } from "next-themes";

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${ClashDisplay.variable} font-clashDisplay `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
